const data = {
    products: [
        {
            name: 'rafu',
            slug: 'rafu',
            category: 'petit-mobilier',
            image: '/images/p1.jpg',
            price: 20,
            countInStock:10,
            brand: 'STEP',
            rating:4.5,
            numReviews: 10,
            description: 'high quality',
        },
        {
            name: 'mwenyekiti',
            slug: 'mwenyekiti',
            category: 'chaise',
            image: '/images/p2.jpg',
            price: 50,
            countInStock:10,
            brand: 'STEP',
            rating:4.5,
            numReviews: 10,
            description: 'high quality',
        },
        {
            name: 'sofa',
            slug: 'sofa',
            category: 'canape',
            image: '/images/p3.jpg',
            price: 700,
            countInStock:10,
            brand: 'SOFA',
            rating:4.5,
            numReviews: 10,
            description: 'high quality',
        },
        {
            name: 'matelas',
            slug: 'matelas',
            category: 'literie',
            image: '/images/p4.jpg',
            price: 20,
            countInStock:10,
            brand: 'STEP',
            rating:4.5,
            numReviews: 10,
            description: 'high quality',
        },
    ],
};

export default data;